- name: install pgbouncer
  apt:
    pkg: pgbouncer
    state: "{{ pgbouncer_install_state }}"
    update_cache: yes
    cache_valid_time: 3600

- name: install postgresql-client
  apt:
    pkg: postgresql-client
    state: present
  when: pgbouncer_install_psql

- name: Create userlist.txt
  command: psql -Upostgres -q -d postgres -c "COPY (SELECT usename, passwd FROM pg_shadow WHERE usename='pgbouncer') TO '/etc/pgbouncer/userlist.txt' WITH (FORMAT CSV, DELIMITER ' ', FORCE_QUOTE *)"

- name: Move functions to server
  copy:
    src: "{{ role_path }}/files/function.sql"
    dest: /tmp/function.sql

- name: Run function.sql
  command: psql -Upostgres -f /tmp/function.sql {{ item.name }}
  loop: "{{ postgresql_databases }}"

- name: template config files
  template:
    src: "{{ item }}"
    dest: /etc/pgbouncer/{{ item | basename | splitext | first }}
    backup: yes
    owner: postgres
    group: postgres
    mode: 0640
  with_fileglob: templates/*
  notify: "restart pgbouncer"
